// user
export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const START_LOGOUT = 'START_LOGOUT';

export const START_REGISTER = 'START_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';

// store
export const UPDATE_STORE = 'UPDATE_STORE'

// request
export const START_LIST_DATA = 'START_LIST_DATA';
export const SUCCESS_LIST_DATA = 'SUCCESS_LIST_DATA';
export const ERROR_LIST_DATA = 'ERROR_LIST_DATA';
export const NO_MORE_LIST_DATA = 'NO_MORE_LIST_DATA';
export const START_REFRESH_DATA = 'START_REFRESH_DATA';
export const SUCCESS_REFRESH_DATA = 'SUCCESS_REFRESH_DATA';

// api
export const START_FETCH = 'START_FETCH';

// portfolios
export const MODIFY_CURRENT_PORTFOLIOS_ID = 'MODIFY_CURRENT_PORTFOLIOS_ID';