// cryptoCurrencies
export const START_FETCH_CRYTPO_CURRENCIES = 'START_FETCH_CRYTPO_CURRENCIES';
export const END_FETCH_CRYTPO_CURRENCIES = 'END_FETCH_CRYTPO_CURRENCIES';
export const ERROR_FETCH_CRYTPO_CURRENCIES = 'ERROR_FETCH_CRYTPO_CURRENCIES';

export const ADD_FAV_CRYPTO_CURRENCY = 'ADD_FAV_CRYPTO_CURRENCY';
export const REMOVE_FAV_CRYPTO_CURRENCY = 'REMOVE_FAV_CRYPTO_CURRENCY';

// myCoins

export const MY_COINS_START_CREATE = 'MY_COINS_START_CREATE';
export const MY_COINS_END_CREATE = 'MY_COINS_END_CREATE';
export const MY_COINS_ERROR_CREATE = 'MY_COINS_ERROR_CREATE';
